services:
  s-one:
    build:
      context: ./server
    networks:
      - writtes-net
  s-two:
    build:
      context: ./server
    networks:
      - writtes-net
  s-three:
    build:
      context: ./server
    networks:
      - writtes-net
  app:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:443"
    networks:
      - writtes-net
networks:
  writtes-net:
    driver: bridge
