services:
  s-one:
    build:
      context: ./server
    networks:
      - writtes-net
  s-two:
    build:
      context: ./server
    networks:
      - writtes-net
  s-three:
    build:
      context: ./server
    networks:
      - writtes-net
  s-four:
    build:
      context: ./server
    networks:
      - writtes-net
  app:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - s-one
      - s-two
      - s-three
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    networks:
      - writtes-net
    restart: unless-stopped
networks:
  writtes-net:
    driver: bridge
