# Trust Cloudflare
real_ip_header CF-Connecting-IP;
real_ip_recursive on;

set_real_ip_from 173.245.48.0/20;
set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 104.16.0.0/13;
set_real_ip_from 104.24.0.0/14;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 131.0.72.0/22;


# server containers
upstream server_clusters {
        least_conn;

        server s-one:3000;
        server s-two:3000;
        server s-three:3000;
}

server {
    listen 80;
    server_name writtes.com www.writtes.com api.writtes.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}


server {
        listen 443 ssl http2;
        server_name writtes.com;

        # paths to ssl certification
        ssl_certificate /etc/letsencrypt/live/writtes.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/writtes.com/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
}

server {
    listen 443 ssl http2;
    server_name api.writtes.com;

    # paths to ssl certification
    ssl_certificate /etc/letsencrypt/live/writtes.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/writtes.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location /api/ {
        proxy_pass http://server_clusters;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}