upstream server_clusters {
        least_conn;

        server s-one:3000;
        server s-two:3000;
        server s-three:3000;
}

server {
        listen 8080;
        server_name localhost;

        # Serve frontend static files
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Reverse proxy to backend server
        location = /api { 
            return 301 /api/;
        }
        
        location /api/ {
            proxy_pass http://server_clusters;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
}